# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

x-kong-image: &kong-image
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    KONG_DATABASE: postgres
    KONG_PG_HOST: postgres
    KONG_PG_PORT: 5432
    KONG_PG_DATABASE: kong
    KONG_PG_SCHEMA: public
    KONG_PG_USER: kong
    KONG_PG_PASSWORD: kong
    KONG_LOG_LEVEL: debug
    KONG_PROXY_ACCESS_LOG: /dev/stdout
    KONG_ADMIN_ACCESS_LOG: /dev/stdout
    KONG_PROXY_ERROR_LOG: /dev/stderr
    KONG_ADMIN_ERROR_LOG: /dev/stderr
    KONG_ADMIN_LISTEN: 0.0.0.0:8001

services:
  kong_init:
    <<: *kong-image
    depends_on:
      - postgres
    entrypoint: [ "/bin/sh", "-c", "until kong migrations bootstrap; do echo waiting for database; sleep 2; done;" ]
  kong:
    <<: *kong-image
    depends_on:
      kong_init:
        condition: service_completed_successfully
    entrypoint: ["/bin/sh", "-c", "KONG_NGINX_DAEMON='off' kong start"]
    ports:
      - "8000:8000"
      - "8001:8001"
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
  tests:
    image: badouralix/curl-jq
    depends_on:
      - kong
    volumes:
      - ./tests:/opt/tests:ro
    entrypoint: [ "/bin/sh", "-c", "cd /opt/tests && ./run_tests.sh" ]

